version: "2.1"
services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy
    container_name: babybuddy
    env_file: .env
    volumes:
      - ./config:/config
    ports:
      - 127.0.0.1:8000:8000
    restart: unless-stopped
volumes:
  config:
